#!/usr/bin/env ruby

require 'thor'

Version = '0.0.1'

class YoCommand < Thor
  default_command :help

  map %w[-v --vesion] => :print_version
  desc '-v, --version', 'バージョン'
  def print_version
    puts "yo v.#{Version}"
  end

  desc 'say' , '言う'
  def say
      puts 'yo!'
  end

end

YoCommand.start(ARGV)
